name: Pi

on:
  push:
    paths-ignore:
      - 'README.md'
  schedule:
    - cron: 0 * * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      on: ${{ github.event_name }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ./tokens.txt
          key: build-${{ github.run_id }}
          restore-keys: |
            build-
      - name: start
        if: always()
        env:
          userpass: ${{ secrets.userpass }}
        run: |
          python  pi.py
