name: Pi

on:
  push:
    paths-ignore:
      - 'README.md'
  schedule:
    - cron: 0 12 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Account 1
        env:
          token: ${{ secrets.token1 }}
        run: |
          python -u pi.py
      - name: Account 2
        env:
          token: ${{ secrets.token2 }}
        run: |
          python -u pi.py
      - name: Account 3
        env:
          token: ${{ secrets.token3 }}
        run: |
          python -u pi.py
      - name: Account 4
        env:
          token: ${{ secrets.token4 }}
        run: |
          python -u pi.py
      - name: Account 5
        env:
          token: ${{ secrets.token5 }}
        run: |
          python -u pi.py
      - name: Account 6
        env:
          token: ${{ secrets.token6 }}
        run: |
          python -u pi.py
