name: Pi

on:
  push:
    paths-ignore:
      - 'README.md'
  schedule:
    - cron: 0 12 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ./tokens.txt
          key: build-${{ github.run_id }}
          restore-keys: |
            build-
      - name: Account 1
        if: always()
        env:
          userpass: ${{ secrets.userpass1 }}
        run: |
          python -u pi.py
      - name: Account 2
        if: always()
        env:
          userpass: ${{ secrets.userpass2 }}
        run: |
          python -u pi.py
      - name: Account 3
        if: always()
        env:
          userpass: ${{ secrets.userpass3 }}
        run: |
          python -u pi.py
      - name: Account 4
        if: always()
        env:
          userpass: ${{ secrets.userpass4 }}
        run: |
          python -u pi.py
      - name: Account 5
        if: always()
        env:
          userpass: ${{ secrets.userpass5 }}
        run: |
          python -u pi.py
      - name: Account 6
        if: always()
        env:
          userpass: ${{ secrets.userpass6 }}
        run: |
          python -u pi.py
